//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldTraffordLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Book()
        {
            this.tbl_LoanVoucherDetail = new HashSet<tbl_LoanVoucherDetail>();
        }
    
        public int AutoID { get; set; }
        public string BookID { get; set; }
        public string QuickCode { get; set; }
        public string BookTitle { get; set; }
        public string TypeOfBook { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Position { get; set; }
        public string Content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanVoucherDetail> tbl_LoanVoucherDetail { get; set; }
    }
}
