//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldTraffordLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LoanVoucher()
        {
            this.tbl_LoanVoucherDetail = new HashSet<tbl_LoanVoucherDetail>();
        }
    
        public int AutoID { get; set; }
        public string VoucherID { get; set; }
        public string ReaderID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsConfirmLoan { get; set; }
        public Nullable<System.DateTime> CofirmLoanTime { get; set; }
        public Nullable<bool> IsConfirmReturn { get; set; }
        public Nullable<System.DateTime> CofirmReturnTime { get; set; }
    
        public virtual tbl_Reader tbl_Reader { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanVoucherDetail> tbl_LoanVoucherDetail { get; set; }
    }
}
