//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldTraffordLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanVoucherDetail
    {
        public int AutoID { get; set; }
        public string VoucherID { get; set; }
        public string BookID { get; set; }
        public Nullable<int> NumOfLoan { get; set; }
    
        public virtual tbl_Book tbl_Book { get; set; }
        public virtual tbl_LoanVoucher tbl_LoanVoucher { get; set; }
    }
}
